data:
  # src_pc1: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_6_neigh_on_target\test_speed_up_to_lvl_8\swisssurface3d_2018_2589-1169_2056_5728.ply
  # src_pc2: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_6_neigh_on_target\test_speed_up_to_lvl_8\swisssurface3d_2024_2589-1169_2056_5728.ply
  # src_pc1: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_7_different_max_correspondances\down_to_0.2\swisssurface3d_2018_2589-1169_2056_5728.ply
  # src_pc2: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_7_different_max_correspondances\down_to_0.2\swisssurface3d_2024_2589-1169_2056_5728.ply
  src_pc1: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_6_neigh_on_target\test_speed_up_to_lvl_8\swisssurface3d_2018_2589-1169_2056_5728.ply
  src_pc2: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_6_neigh_on_target\test_speed_up_to_lvl_8\swisssurface3d_2024_2589-1169_2056_5728.ply
  # src_pc1: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_9_icp_per_class\buildings\swisssurface3d_2018_2589-1169_2056_5728_buildings.ply
  # src_pc2: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_9_icp_per_class\buildings\swisssurface3d_2024_2589-1169_2056_5728_buildings.ply
  # src_pc1: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_0_subsample\swisssurface3d_2018_2589-1169_2056_5728_subsample.ply
  # src_pc2: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_0_subsample\swisssurface3d_2024_2589-1169_2056_5728_subsample.ply
  src_res: default
  # res_suffixe: "2500_1144_quadtree_20k"
  res_suffixe: "test"
args:
  method: pointtoplane  # choose between pointtopoint and pointtoplane
  pointtoplane_radius: 1.0
  pointtoplane_max_nn: 30
  max_level: 12
  min_points: 500
  huge_translation: [2589500, 1169500, 0]
  # huge_translation: [0,0,0]
  do_output_transformed: True
  output_level: 8 # -1 to output at each level