data:
  # src_pc1: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_min_points\3000_max_lvl_7\swisssurface3d_2018_2589-1169_2056_5728.ply
  # src_pc2: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\test_min_points\3000_max_lvl_7\swisssurface3d_2024_2589-1169_2056_5728.ply
  src_pc1: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\temp\swisssurface3d_2018_2589-1169_2056_5728_subsample.ply
  src_pc2: D:\GitHubProjects\Terranum_repo\pc_movement_tracking\data\temp\swisssurface3d_2024_2589-1169_2056_5728_subsample.ply
  src_res: default
  # res_suffixe: "2500_1144_quadtree_20k"
  res_suffixe: "test"
args:
  method: pointtoplane  # choose betwee pointtopoint and pointtoplane
  pointtoplane_radius: 1.0
  pointtoplane_max_nn: 30
  max_level: 6
  min_points: 1000
  huge_translation: [2589500, 1169500, 0]
  # huge_translation: [0,0,0]
  do_output_transformed: False
  output_level: -1 # -1 to output at each level